### ISSUE TITLE
Templates: isolate build data

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#169]
When I do e.g. `Object.assign` in template while running `mango d` it does have some weird side effects.

**Comment by ViliamKopecky** [comment]
Probably deep-cloning template variables for each render.

**Comment by enzy** [comment]
This is the part, which is responsible for data providing. It already uses `cloneDeep` and `assign`.

```js
.pipe(data(function(file) {
	var name = path.basename(file.path)
	var data = _.cloneDeep(templatesData)

	// In case of name == key, assign value as global object
	if(typeof templatesData[name] !== 'undefined') {
		var obj = _.assign(data, templatesData[name], file.data)
		return obj
	} else {
		var obj = _.assign(data, file.data)
		return obj
	}
}))
```

Which weird side effects are you talking about? @Cactucs

**Comment by enzy** [comment]
Maybe try a slightly refactored code here: a82f376420d0593b0a34367140eb7824c6281b35
