### ISSUE TITLE
NPM install of node-sass fails on node v0.11.14

### ISSUE THREAD

**Issue by enzy** [manGoweb/mango-cli#20]
Upstream: https://github.com/sass/node-sass/issues/550

**Comment by askdesigners** [comment]
Holy shit I think this node-sass module is broken. Ive been banging my head against it for the past 2 days in a different project. Do you get a failure when it tries to compile with node-gyp?

**Comment by enzy** [comment]
Do you have all requirements mentioned here: https://github.com/TooTallNate/node-gyp#installation ?
