### ISSUE TITLE
Neinstalovat globálně

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#230]
Tím nebudeme mít následující problémy:
- Jednoduché používání více verzí
- Zpětná kompatibilita

**Comment by HonzaMatosik** [comment]
Lze používat https://github.com/manGoweb/mango-cli-wrapper

**Comment by Cactucs** [comment]
@HonzaMatosik 
> Jednoduché

...a navíc tam prý nefunguje dev mode

**Comment by HonzaMatosik** [comment]
dev mode funguje.
Má to jen 2 bugy:
- není odchyceno Ctrl C pro ukončení
- Není nastavený port propojujích lokální sít a docker

Obojí má easy fix

**Comment by Cactucs** [comment]
Ale není to jednoduché

**Comment by enzy** [comment]
It's a CLI tool meant to be installed globally to share and update current development workflow across multiple project easily. Yes, it has some drawbacks to stay up to date on the older projects but not any critical ones.

More on the all ways how to use different version in the [wiki](https://github.com/manGoweb/mango-cli/wiki/FAQ#how-to-use-multiple-versions-of-mango-cli).
