### ISSUE TITLE
Deprecate proxy

### ISSUE THREAD

**Issue by ViliamKopecky** [manGoweb/mango-cli#27]
Proxy does messy things. Lets get rid of it.

Imagine:
- start `mango dev`
- browsersync starts its websocket service on some port
- browsersync generates snippet code and saves it into temporary file on project's root `/.bs-snippet`
- snippet is supposed to load browser-sync script, which should have its port hardcoded - not retrieving port from client-side (because browser-sync doesnt run on the same port as web)
- on mango dev quit delete the temporary file

**Comment by enzy** [comment]
@ViliamKopecky you did some work on this so what about documenting it in the wiki?

**Comment by enzy** [comment]
bump @ViliamKopecky

**Comment by enzy** [comment]
ping @ViliamKopecky

**Comment by enzy** [comment]
pong @ViliamKopecky

**Comment by enzy** [comment]
dong @ViliamKopecky

**Comment by enzy** [comment]
:cat: @ViliamKopecky

**Comment by enzy** [comment]
obsolete
