### ISSUE TITLE
init behaviour same as git clone

### ISSUE THREAD

**Issue by tsusanka** [manGoweb/mango-cli#39]
The command `mango init --source foo/bar` clones the repo into the current folder (am I wrong?). Would be nice if it used the `git clone` behaviour, ie `mango init --source foo/bar` creates the folder `bar` and clones the repo into it.

**Comment by enzy** [comment]
```
λ mango init -h

  Usage: init [options] [directory]

  initialize a new project

  Options:

    -h, --help                     output usage information
    -s, --source [git_repository]  Template repository to fork. Defaults to https://github.com/frontbase/Frontbase.git
```

**Comment by ViliamKopecky** [comment]
I dare to agree with @tsusanka

**Comment by enzy** [comment]
All commands work in current folder, but PR is welcome ;)

**Comment by tsusanka** [comment]
How about we replace `mango init --source` with `mango clone`. It will be logical and git-related. What do you think?

**Comment by enzy** [comment]
Clone is the first step implemented only, more will come and the clone word would not correspond.

**Comment by tsusanka** [comment]
I don't get it :(. Could you elaborate that?

**Comment by ViliamKopecky** [comment]
@tsusanka project initialization (`mango init`) is more steps than just cloning the repo... but for now just this step is implemented. For future it could set permissions, install dependencies, ask for database connection, ...

**Comment by tsusanka** [comment]
ah I see. Hmm, so fuck it?

**Comment by ViliamKopecky** [comment]
fuck it
