### ISSUE TITLE
Published package to npm does not work on Unix machines

### ISSUE THREAD

**Issue by tsusanka** [manGoweb/mango-cli#40]
Windows machines use, by default, `\r\n` as a line feed. When you commit to git, it's all good because of the git setting that usually commits Unix style line feeds. If you publish to npm on Windows, then you're zipping up and sending the files and thus get `\r\n` published. That causes strange error on linux:  `: No such file or directory.`. See https://github.com/npm/npm/issues/2097 and [SO question](https://stackoverflow.com/questions/27331758/linux-nodejs-global-npm-package-no-such-file-or-directory) for details.

Should be fixed easily by using `git config core.autocrlf` that deletes the `\r\n`. And then publish. Or simply publish it on a proper OS.

**Comment by tsusanka** [comment]
@ViliamKopecky also would help if you setup your git to auto correct this, @JanTvrdik can give further info :)

**Comment by enzy** [comment]
Strange it doesn't cause any problems on MacOS. Are all packages published in wrong format or just from Viliam?

**Comment by tsusanka** [comment]
What do you mean all packages? It seems to me that all packages published to npm with `\r\n` are non-working on unix.

**Comment by ViliamKopecky** [comment]
@tsusanka Please test the `0.9.2` release (published from OS X)

**Comment by tsusanka** [comment]
Works! Thank you
