### ISSUE TITLE
Some sort of lazy installation

### ISSUE THREAD

**Issue by enzy** [manGoweb/mango-cli#46]
Goals:
- reduce installation / upgrade time to minimum
- allow project to include more libraries

Maybe with help of https://github.com/bevry/lazy-require

**Comment by enzy** [comment]
Or install it as a bundle directly https://github.com/zeit/pkg

**Comment by Cactucs** [comment]
I have some WIP version of lazy install... But needs lots of work. 

(Also I have  @mango-cli org on npm.)
