### ISSUE TITLE
Proper Handlebars support

### ISSUE THREAD

**Issue by enzy** [manGoweb/mango-cli#47]
- [ ] Handlebars engine (started in #44, switch to [gulp-hb](https://github.com/shannonmoeller/gulp-hb) / [Assemble](http://assemble.io))
- [ ] Layouts
- [ ] Partials
- [x] A way to feed templates with data - [gulp-data](https://github.com/colynb/gulp-data) / [front-matter](https://github.com/lmtm/gulp-front-matter)
- [ ] easy (or zero) configuration

**Comment by simi** [comment]
:+1: for `gulp-front-matter` since `gulp-data` will be really hard to configure.
