### ISSUE TITLE
Not enough info about fail in dev command 

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#56]
When I run `dev` command it says:

```
~ styles
Error in plugin 'run-sequence'
Message:
    An error occured in task 'styles'.
```

But when I try `build` command it outputs:
```
~ styles
~ compilation time: 766ms
Error: The `libsass` binding was not found in /usr/local/lib/node_modules/mango-cli/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
```

I think it would be better to output this also in dev command.

**Comment by enzy** [comment]
Dev mode catches all errors and prints them in a more friendly way. We are using the [gulp-plumber](https://github.com/floatdrop/gulp-plumber) and a `error.toString()` method for that.

Your error is an edge case which don't happen regularly.

I assume you did a Node upgrade from 0.12 to 4.x?

**Comment by Cactucs** [comment]
Yes I did... And still trying to solve it...

**Comment by enzy** [comment]
Yep, you must remove node_modules and install them again. (It's upstream error which we cannot solve)
