### ISSUE TITLE
Jade to JS

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#57]
Is there a way to compile from Jade template file to JS and use it in front-end scripts?

Can be done by `client: true` option in gulp-jade. But as far as I know mango-cli has hardcoded option for gulp-jade so I can't change it from config. Is that true?

**Comment by enzy** [comment]
It is hardcoded for now but it can be changed quite easily. PR is welcome :)

Should follow this convention:
```
false - turn off
undefined - default options
object - default options extended with custom values
```

**Comment by Cactucs** [comment]
I found [here](https://github.com/manGoweb/mango-cli/blob/master/lib/tasks/styles.js#L67) and [here](https://github.com/manGoweb/mango-cli/blob/master/lib/tasks/styles.js#L53) that it doesn't follow this convention. 

Actually I didn't found any code which would follow this convention - so I can copy&paste it ;)

**Comment by enzy** [comment]
Its an ongoing effort to unify these options into the same behaviour...

Thanks for the contribution btw!
