### ISSUE TITLE
Custom tasks?

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#59]
I'm thinking of a feature which would allow me to add custom (project-specific) gulp task. Let me explain in a example:
I want to use Jade as front-end templating. That means I would like to generate .js template files (solved in issue #57) and get it via CommonJS module (normally done by gulp-webmake). 

I see to two solutions. One is add generating Jade template in JS and import as module to the mongo-cli source. I think this is better in the basic vision of mango-cli (everything is in the configuration file). But then there will be need to add a lots of things so mango-cli gets really bigger. 
The other solution is to add this custom task feature and solve "everything". 

I more and more I think about it I think that it's better to add it to mongo-cli, because it makes bigger sense (because when we add custom task feature we are nearly back in vanilla gulp).
What's the "official" opinion?

**Comment by enzy** [comment]
And there is a third option:  [hooks](https://github.com/manGoweb/mango-cli/blob/master/docs/config.md#hooks)

**Comment by Cactucs** [comment]
But command line is not platform independent. And it's harder to build such a thing in hooks than it would be with custom taks. And making gulp to run gulp task via command line (that's how I would solve it) sound stupid.

**Comment by enzy** [comment]
We can extend hooks to detect a filename instead of commands and run them in the node with some arguments.
*mango-cli* is about workflow, not tools used under the hood. Exposing Gulp is not a good idea because it can be someday replaced with something else.

**Comment by Cactucs** [comment]
Sounds good. I wouldn't personally be against exposing gulp, because mongo-cli is from the basics built on top of gulp and when you try to do something a bit advance (e.g. configuring) it's changes specific to gulp (or gulp-dependent's packages). In case of migration to another tool it wouldn't be back compatible anyway and exposing gulp can be done quite easily even when using another tool (it would create gulp just for custom task).
