### ISSUE TITLE
Production config

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#62]
I have config in .js file: 
``` JS
module.exports = {
   api: 'http://locahost:8000/'
};
```
I use this config when I do API calls to server. But then I deploy it to production. Everything seems to work well, but on others' computers not. I forgot to change this every time I do a deployment. 

My solution: I would like to have two files: `config.js` and `config.production.js` and when the production build is performed (`mango b`) then the production config will be used. In development mode the "normal" one will be used. 

Do you have another solution? Do you like this one?

Implementation: Something like:
``` JS
"production-aliases": {
  "config.js": "config.production.js"
}
```

**Comment by enzy** [comment]
This should be responsibility of the application. (like Nette local config etc.)

**Comment by Cactucs** [comment]
But to do it in-app automatically you need know if you are on production or in development. But JavaScript does not have anything like `window.isInProduction()`. I don't to do it "magically" e.g. using `window.location.hostname`. 

I think the parallel with Nette is not working because you are deploying exactly what you have on localhost. That's not how it is done with mango-cli based project. 

In nette projects I have seen two approaches to the local config. First wasn't deploying the config.local.neon file at all (ignored it). The second one has done something like this:
``` PHP
if(file_exists('config.local.neon')) {
  $configurator->addConfig('config.local.neon');
} else {
  $configurator->addConfig('config.production.neon');
}
```
But because it's bundling the JavaScript these method can not be applied to this use case. 

PS: I don't like the idea of loading both config to client.

**Comment by enzy** [comment]
When in a development mode, there is the `DEBUG` global flag replaced to `true` (and `false` in production build) in all JavaScript files processed by the mango-cli.

Also you can build files during a development process and there you can have a `mango.local.json` which rewrites the config as you need to.

**Comment by Cactucs** [comment]
:+1: 

I solved it by:
``` JS
module.exports = {
   api: DEBUG ? 'http://locahost:8000/' : 'http://production.tld/'
};
```

Thanks!

*(Not best solution but simplest)*
