### ISSUE TITLE
Running not as global command

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#65]
I am trying to test a change I made: Impossible...

This is the error output:
```
~/p/m/e/frontbase (master) > node ../../bin/mango d
Starting development mode
~ cleaning dist folder
~ styles
Error in plugin 'run-sequence'
Message:
    An error occured in task 'styles'.
~/p/m/e/frontbase (master) > nodejs ../../bin/mango d
Starting development mode
~ cleaning dist folder
~ styles
fish: “nodejs ../../bin/mango d” terminated by signal SIGBUS (Misaligned address error)
~/p/m/e/frontbase (master) > node -v
v5.0.0
~/p/m/e/frontbase (master) > nodejs -v
v4.2.2
```

How are you testing changes? 

(Don't really understand what's going on)

**Comment by enzy** [comment]
If you change a Node version, you must reinstall all node modules from scratch.

If you want to run the mango-cli from a clonned repo, remove a global version and then run `npm link` from a repo directory.

**Comment by Cactucs** [comment]
Thank's. I had mess in my node.js versions... Made it cleaner and reinstalled node modules. Made a sym link to be able to execute mango as global command. Working! Thanks!
