### ISSUE TITLE
Investigate use of Webpack instead of Webmake

### ISSUE THREAD

**Issue by enzy** [manGoweb/mango-cli#69]
https://webpack.js.org

**Comment by enzy** [comment]
ad webpack: we would like to build on version 2.0+ which is still in development

**Comment by Cactucs** [comment]
Maybe use code-splitting... (Would be great for components as used in mango-cli-example)

**Comment by Onset** [comment]
@Cactucs Code-splitting adds too big overhead for our small projects and we are the only users of mango-cli yet. I've been recently working on a project with 26 mango-cli-example components like. The compiled `script.js` had only 20 KB. Getting rid of jQuery which has 30 KB would make much more difference.
