### ISSUE TITLE
Default repo

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#74]
IMHO the project "generated" with `mango init` command should be more empty, so less deleting has to be done.

**Comment by ViliamKopecky** [comment]
Yes. Would you like to prepare it? Would be nice to have some prepared boilerplates for different types of projects.

**Comment by Cactucs** [comment]
I can... I'm thinking of using yoman... To choose styl/sass/less etc.

**Comment by ViliamKopecky** [comment]
Good idea! Shall I create a repository? Probably mangoweb/mango-cli-boilerplate(-generator)

**Comment by Cactucs** [comment]
:+1:
