### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by Cactucs** [manGoweb/mango-cli#93]
See #92 ;-)

**Comment by enzy** [comment]
That's an error in a pipe which is fatal and mysterious sometimes. We have implemented the Plumber but it doesn't help sometimes...

**Comment by Cactucs** [comment]
Submitted https://github.com/OverZealous/run-sequence/issues/65

**Comment by Cactucs** [comment]
:tada: Meerged! Now update run-sequence package to 1.2

**Comment by Cactucs** [comment]
https://github.com/terinjokes/gulp-uglify/blob/master/docs/why-use-pump/README.md#using-pump
