### ISSUE TITLE
Nonexistence of node_modules makes wrong paths

### ISSUE THREAD

**Issue by ViliamKopecky** [manGoweb/mango-cli#98]
Dont know how... but when project doesnt have node_modules dir, it makes weird require file structure.

**Comment by enzy** [comment]
'node_modules' is the default directory to look for modules. Were the paths relative or absolute?

You could also make a test for this :)

**Comment by ViliamKopecky** [comment]
Mango decides this on its init... When you create/delete `node_modules` during dev mode, it doesnt change.

```
correct:
www/src/scripts/index

wrong:
/ekola/www/src/scripts/index

mango root:
W:/rekola/www
```

**Comment by enzy** [comment]
- [ ] Make a test from this
